spring:
  datasource:
    url: jdbc:h2:file:./data/mp5
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: "/h2-console"
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: always
