
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER)
VALUES (10, 'Anna', 'Kowalska', 'anna.kowalska@example.com', '123456789');
INSERT INTO STUDENT (ID,INDEX)
VALUES (10,'s123456');

INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER)
VALUES (11, 'tom', 'nowak', 'nowak@example.com', '123456789');
INSERT INTO STUDENT (ID,INDEX)
VALUES (11,'s123456');

INSERT INTO group_uni (ID, NAME, TYPE)
VALUES (10, 'asdasd', 'wyklad');

INSERT INTO STUDENT_GROUP (ID, STUDENT_ID, GROUP_ID, ACCEPTED_DATE)
VALUES (10, 10, 10, CURRENT_DATE);
INSERT INTO STUDENT_GROUP (ID, STUDENT_ID, GROUP_ID, ACCEPTED_DATE)
VALUES (11, 11, 10, CURRENT_DATE);